name: Crawl Jewish Studies Journals (Crossref)

on: 
  workflow_dispatch:
  schedule:
    # Every Friday at 6:00 AM UTC (weekly run for Friday digest)
    - cron: "0 6 * * 5"

jobs:
  crawl-crossref:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create directories
        run: |
          mkdir -p data/memory
          mkdir -p data/output

      - name: Run Crossref crawler
        run: |
          python crawl_crossref.py
        env:
          PYTHONPATH: .

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Changes detected:"
            git status --porcelain
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          git commit -m "Update research articles - $(date -u '+%Y-%m-%d %H:%M UTC')"
          git push
