name: Crawl Jewish News

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # Hourly

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crawl news feeds
        run: python main.py news
        env:
          CROSSREF_EMAIL: ${{ secrets.CROSSREF_EMAIL }}

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/
          git diff --staged --quiet || git commit -m "News data updated"
          git push origin main
